---
- name: testing copy
  hosts: test
  vars_files:
     - vars.yml
  tasks:
   - name: copy
     copy:
      src: /tmp/file.txt
      dest: /tmp
   - name: template
     template:
      src: /tmp/file.txt
      dest: /opt
  
