---
- name: Docker Swarm
  hosts: test
  tasks:
  - name: testing loop
    yum:
      name: "{{ item }}"
      state: installed
      with_items:
       - yum-utils
       - device-mapper-persistent-data
       - lvm2

