---
- name: Docker Swarm
  hosts: test
  user: ansadm
  become: yes
  become_method: sudo
  tasks:
  - name: Ading yum repo
    yum_repository:
     name: doker_repo
     description: Docker Repository
     baseurl: https://download.docker.com/linux/centos/docker-ce.repo
     gpgcheck: no

  - name: This will install multiple packages using loop function.
    yum:
      name: "{{ item }}"
      state: latest
    loop:
       - yum-utils
       - device-mapper-persistent-data
       - lvm2
       - docker-ce 
       - docker-ce-cli 
       - containerd.io

