---
- name: Playbook for http server
  hosts: test
  tasks:
   - name: http installation
     yum:
      name: httpd
      state: latest
     tags:
       - http
   - name: Start the service 
     service:
      name: httpd
      state: started
      enabled: yes
     tags:
       - service
   - name: copy index file
     copy:
      src: /opt/index.html
      dest: /var/www/html
