---
- name: Playbook for http server
  hosts: test
  vars_files:
    - vars.yml
  tasks:
   - name: http installation {{ name }}
     yum:
      name: httpd
      state: latest
     tags:
       - http
   - name: Start the service 
     service:
      name: httpd
      state: started
      enabled: yes
     tags:
       - service
   - name: copy index file
     copy:
      src: /opt/index.html
      dest: /var/www/html
  
   - name: checking variable
     debug:
      msg: "{{name}}"

